version: '3'

services:
  jenkins-master:
    image: ghcr.io/${REGISTRY}/jenkins-master
    environment:
    - JAVA_OPTS=-Xmx2048m
    volumes:
      - ./data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins-net

  jenkins-worker:
    image: eeacms/jenkins-slave
    environment:
      JAVA_OPTS: "-Xmx2048m"
      JENKINS_MASTER: "http://jenkins-master:8080"
      JENKINS_NAME: "default-worker"
      JENKINS_RETRY: "10"
    env_file:
      - .env
    networks:
      - jenkins-net
    depends_on:
      - jenkins-master

  jenkins-worker-terraform:
    image: ghcr.io/${REGISTRY}/jenkins-slave-terraform
    environment:
      JAVA_OPTS: "-Xmx2048m"
      JENKINS_MASTER: "http://jenkins-master:8080"
      JENKINS_NAME: "terraform"
      JENKINS_RETRY: "10"
    env_file:
      - .env
    networks:
      - jenkins-net
    depends_on:
      - jenkins-master

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d/
    depends_on:
      - jenkins-master
    networks:
      - jenkins-net

networks:
  jenkins-net: