version: '3'

services:
  jenkins-master:
    image: jenkins-master
    build:
      context: ./docker
      dockerfile: ./Dockerfile_master
    container_name: jenkins-master
    expose:
      - 8080
      - 50000
    environment:
    - JAVA_OPTS=-Xmx2048m
    volumes:
      - ./data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins-net

  jenkins-worker:
    image: eeacms/jenkins-slave
    container_name: jenkins-worker
    environment:
      JAVA_OPTS: "-Xmx2048m"
      JENKINS_MASTER: "http://jenkins-master:8080"
      JENKINS_NAME: "default-worker"
      JENKINS_RETRY: "10"
    env_file:
      - .env
    networks:
      - jenkins-net
    depends_on:
      - jenkins-master

  jenkins-worker-terraform:
    image: jenkins-slave-terraform
    build:
      context: ./docker
      dockerfile: ./Dockerfile_terraform_worker
      args:
        TERRAFORM_VERSION: ${TERRAFORM_VERSION}
    container_name: jenkins-worker-terraform
    environment:
      JAVA_OPTS: "-Xmx2048m"
      JENKINS_MASTER: "http://jenkins-master:8080"
      JENKINS_NAME: "terraform"
      JENKINS_RETRY: "10"
    env_file:
      - .env
    networks:
      - jenkins-net
    depends_on:
      - jenkins-master

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d/
    depends_on:
      - jenkins-master
    networks:
      - jenkins-net

networks:
  jenkins-net: