version: '3'

services:
  jenkins-master:
    image: eeacms/jenkins-master
    container_name: jenkins-master
    expose:
      - 8080
      - 50000
    environment:
    - JAVA_OPTS=-Xmx2048m
    volumes:
      - ./data:/var/jenkins_home
    networks:
      - jenkins-net

  jenkins-worker:
    image: eeacms/jenkins-slave
    container_name: jenkins-worker-1
    environment:
      JAVA_OPTS: "-Xmx2048m"
      JENKINS_MASTER: "http://jenkins-master:8080"
      JENKINS_NAME: "worker"
      JENKINS_RETRY: "10"
    env_file:
      - .env
    networks:
      - jenkins-net
    depends_on:
      - jenkins-master

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d/
    depends_on:
      - jenkins-master
    networks:
      - jenkins-net

networks:
  jenkins-net: